---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Plant
    description: the Plant Api
paths:
  "/plant":
    post:
      tags:
        - Plant
      summary: adds a plant
      description: Adds a plant to the list of plants
      operationId: addPlant
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/Plant"
        required: true
      responses:
        '201':
          description: successfully added a plnt
        '409':
          description: duplicate plant
  "/plant/all":
    get:
      tags:
        - Plant
      summary: Fetch all plants
      description: fetches all plant entities and their data from data source
      operationId: getAll
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Plant"
  "/api/messages":
    get:
      tags:
        - message-controller
      operationId: getMessage
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: string
components:
  schemas:
    Plant:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
